### PR TITLE
Allow more characters in email address validator for SRS only

### PR DESCRIPTION
**Pull request by gregkster**
Fixes iRedAPD #7

### CODE REVIEW

**Comment by iredmail** [comment]
Could you help replace `regx_email` by your `regx_email_srs`? No need to use 2 regular expressions. :)

**Comment by gregkster** [comment]
My regx_email_srs allows some invalid addresses (false positives), which I thought might be undesirable for the policy portion of iRedAPD.  Maybe this is a better solution:
https://pypi.org/project/py_email_validation/

**Comment by iredmail** [comment]
Could you please try my latest commit?
https://github.com/iredmail/iRedAPD/commit/b597211f25af10b3030ca526f1f83770938c4f12

**Comment by gregkster** [comment]
Here's my new take based on https://github.com/JoshData/python-email-validator
https://github.com/gregkster/iRedAPD/commit/03599a4e503b6004444d9a9b5564f6805a0f6893

**Comment by iredmail** [comment]
Let's simply update `regx_email` and not introduce new function `is_email_srs()`. :)

**Pull request closed without merging**
